FROM jupyter/scipy-notebook
RUN pip install bigartm10
RUN pip install nltk
RUN python3 -c "import nltk; nltk.download('stopwords')"
RUN pip install pymystem3
RUN pip install gensim
RUN pip install pymystem3
RUN pip install pyLDAvis